version: '{build}'
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - java -version
  - gradlew.bat --version

build_script:
  - gradlew.bat -u -i assemble
test_script:
  - gradlew.bat -u -i -S check

notifications:
- provider: Email
  to:
  - addugger@gmail.com
  subject: 'Build failed: ShapeStacker'
  message: The continuous integration build failed. See https://ci.appveyor.com/project/addugger/shapestacker for details.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
